os:
  - linux
services:
  - docker
language: node_js
node_js:
  - "10.16.3"
cache:
  directories:
    - node
    - node_modules
    - $HOME/.m2
env:
  global:
    - NODE_VERSION=10.16.3
    - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    - SPRING_JPA_SHOW_SQL=false
    - JHI_DISABLE_WEBPACK_LOGS=true
    - NG_CLI_ANALYTICS="false"
before_install:
  - java -version
  - docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
  - nvm install $NODE_VERSION
  - npm install -g npm
  - node -v
  - npm -v
install:
  - npm install
script:
  - chmod +x mvnw
  - ./mvnw -ntp clean verify
  - ./mvnw -ntp verify -Pprod -DskipTests jib:dockerBuild
  - docker images
  - docker image tag appone sumansaurabh/appone
  - docker push sumansaurabh/appone
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
